default: &default
  encoding: unicode
  localhost: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: probe_production
  username: probe_api
  password: <%= ENV['PROBE_DATABASE_PASSWORD'] %>
