default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: probe_dev

test:
  <<: *default
  database: probe_test

production:
  <<: *default
  database: probe_production
  username: probe_api
  password: <%= ENV['PROBE_DATABASE_PASSWORD'] %>
